// Comprehensive UI translations
const translations = {
  en: { name: 'English', flag: '🇬🇧', dir: 'ltr', nav: { back: 'Back' }, hero: { title1: 'Download Any Video', title2: 'For Free', subtitle: 'YouTube, Instagram, TikTok, Facebook & more', body: 'Save directly to your device gallery — no sign-up needed.', hint: '↓ Choose a platform below to get started' }, platformGrid: 'Choose your platform', downloader: { analyze: 'Analyze URL', parsing: 'Parsing...', subtitle: 'Paste your {platform} link below to get started.', defaultSubtitle: 'Paste a video link below to get started.', error: 'Download failed' }, footer: { copyright: 'Copyright © 2026 StreamVault', links: ['About us', 'Contact', 'Terms of Service', 'Privacy Policy'] } },
  hi: { name: 'हिंदी', flag: '🇮🇳', dir: 'ltr', nav: { back: 'वापस' }, hero: { title1: 'कोई भी वीडियो डाउनलोड करें', title2: 'मुफ्त में', subtitle: 'YouTube, Instagram, TikTok, Facebook और अधिक', body: 'सीधे आपकी गैलरी में सेव करें — साइन-अप की जरूरत नहीं।', hint: '↓ शुरुआत के लिए नीचे एक प्लेटफॉर्म चुनें' }, platformGrid: 'अपना प्लेटफॉर्म चुनें', downloader: { analyze: 'URL विश्लेषण करें', parsing: 'हो रहा है...', subtitle: 'नीचे अपना {platform} लिंक पेस्ट करें।', defaultSubtitle: 'नीचे वीडियो लिंक पेस्ट करें।', error: 'डाउनलोड विफल' }, footer: { copyright: 'कॉपीराइट © 2026 StreamVault', links: ['हमारे बारे में', 'संपर्क', 'सेवा की शर्तें', 'गोپनीयता नीति'] } },
  ar: { name: 'العربية', flag: '🇸🇦', dir: 'rtl', nav: { back: 'رجوع' }, hero: { title1: 'تحميل أي فيديو', title2: 'مجاناً', subtitle: 'يوتيوب، انستغرام، تيك توك، فيسبوك والمزيد', body: 'احفظ مباشرةً في معرض جهازك — لا حاجة للتسجيل.', hint: '↓ اختر منصة أدناه للبدء' }, platformGrid: 'اختر منصتك', downloader: { analyze: 'تحليل الرابط', parsing: 'جارٍ التحليل...', subtitle: 'الصق رابط {platform} أدناه للبدء.', defaultSubtitle: 'الصق رابط فيديو أدناه للبدء.', error: 'فشل التنزيل' }, footer: { copyright: 'حقوق النشر © 2026 StreamVault', links: ['من نحن', 'اتصل بنا', 'شروط الخدمة', 'سياسة الخصوصية'] } },
  bn: { name: 'বাংলা', flag: '🇧🇩', dir: 'ltr', nav: { back: 'ফিরে যান' }, hero: { title1: 'যেকোনো ভিডিও ডাউনলোড করুন', title2: 'বিনামূল্যে', subtitle: 'ইউটিউব, ইনস্টাগ্রাম, টিকটক, ফেসবুক এবং আরও অনেক কিছু', body: 'সরাসরি আপনার ডিভাইসের গ্যালারিতে সংরক্ষণ করুন — কোনো সাইন-আপের প্রয়োজন নেই।', hint: '↓ শুরু করতে নিচে একটি প্ল্যাটফর্ম চয়ন করুন' }, platformGrid: 'আপনার প্ল্যাটফর্ম চয়ন করুন', downloader: { analyze: 'URL বিশ্লেষণ করুন', parsing: 'বিশ্লেষণ করা হচ্ছে...', subtitle: 'শুরু করতে নিচে আপনার {platform} লিঙ্ক পেস্ট করুন।', defaultSubtitle: 'নিচে একটি ভিডিও লিঙ্ক পেস্ট করুন।', error: 'ডাউনলোড ব্যর্থ হয়েছে' }, footer: { copyright: 'কপিরাইট © ২০২৬ StreamVault', links: ['আমাদের সম্পর্কে', 'যোগাযোগ', 'পরিষেবার শর্তাবলী', 'গোপনীয়তা নীতি'] } },
  mr: { name: 'मराठी', flag: '🇮🇳', dir: 'ltr', nav: { back: 'मागे' }, hero: { title1: 'कोणताही व्हिडिओ डाउनलोड करा', title2: 'मोफत', subtitle: 'YouTube, Instagram, TikTok, Facebook आणि अधिक', body: 'थेट तुमच्या डिव्हाइसच्या गॅलरीत सेव्ह करा — साइन-अपची गरज नाही.', hint: '↓ सुरू करण्यासाठी खाली एक प्लॅटफॉर्म निवडा' }, platformGrid: 'तुमचा प्लॅटफॉर्म निवडा', downloader: { analyze: 'URL विश्लेषण', parsing: 'विश्लेषण सुरू आहे...', subtitle: 'सुरू करण्यासाठी खाली तुमचा {platform} दुवा पेस्ट करा.', defaultSubtitle: 'खाली व्हिडिओ दुवा पेस्ट करा.', error: 'डाउनलोड अयशस्वी' }, footer: { copyright: 'कॉपीराइट © २०२६ StreamVault', links: ['आमच्याबद्दल', 'संपर्क', 'सेवा अटी', 'गोपनीयता धोरण'] } },
  te: { name: 'తెలుగు', flag: '🇮🇳', dir: 'ltr', nav: { back: 'వెనుకకు' }, hero: { title1: 'ఏదైనా వీడియోను డౌన్‌లోడ్ చేయండి', title2: 'ఉచితంగా', subtitle: 'YouTube, Instagram, TikTok, Facebook ఇంకా మరిన్ని', body: 'నేరుగా మీ పరికర గ్యాలరీకి సేవ్ చేయండి — సైన్-అప్ అవసరం లేదు.', hint: '↓ ప్రారంభించడానికి దిగువన ప్లాట్‌ఫారమ్‌ను ఎంచుకోండి' }, platformGrid: 'మీ ప్లాట్‌ఫారమ్‌ను ఎంచుకోండి', downloader: { analyze: 'URL విశ్లేషించండి', parsing: 'విశ్లేషిస్తోంది...', subtitle: 'ప్రారంభించడానికి దిగువన మీ {platform} లింక్‌ను అతికించండి.', defaultSubtitle: 'దిగువన వీడియో లింక్‌ను అతికించండి.', error: 'డౌన్‌లోడ్ విఫలమైంది' }, footer: { copyright: 'కాపీరైట్ © 2026 StreamVault', links: ['మా గురించి', 'సంప్రదించండి', 'సేవా నిబంధనలు', 'గోప్యతా పాలసీ'] } },
  ta: { name: 'தமிழ்', flag: '🇮🇳', dir: 'ltr', nav: { back: 'பின்னால்' }, hero: { title1: 'எந்த வீடியோவையும் பதிவிறக்கவும்', title2: 'இலவசமாக', subtitle: 'YouTube, Instagram, TikTok, Facebook மற்றும் பல', body: 'நேரடியாக உங்கள் சாதன கேலரியில் சேமிக்கவும் — பதிவு தேவையில்லை.', hint: '↓ தொடங்க கீழே ஒரு தளத்தைத் தேர்ந்தெடுக்கவும்' }, platformGrid: 'உங்கள் தளத்தைத் தேர்ந்தெடுக்கவும்', downloader: { analyze: 'URL பகுப்பாய்வு', parsing: 'பகுப்பாய்வு செய்யப்படுகிறது...', subtitle: 'தொடங்க கீழே உங்கள் {platform} இணைப்பை ஒட்டவும்.', defaultSubtitle: 'கீழே வீடியோ இணைப்பை ஒட்டவும்.', error: 'பதிவிறக்கம் தோல்வியடைந்தது' }, footer: { copyright: 'பதிப்புரிமை © 2026 StreamVault', links: ['எங்களைப் பற்றி', 'தொடர்பு கொள்ள', 'சேவை விதிமுறைகள்', 'தனியுரிமைக் கொள்கை'] } },
  gu: { name: 'ગુજરાતી', flag: '🇮🇳', dir: 'ltr', nav: { back: 'પાછા' }, hero: { title1: 'કોઈપણ વિડિઓ ડાઉનલોડ કરો', title2: 'મફતમાં', subtitle: 'YouTube, Instagram, TikTok, Facebook અને વધુ', body: 'સીધા તમારા ઉપકરણની ગેલેરીમાં સાચવો — સાઇન-અપની જરૂર નથી.', hint: '↓ શરૂ કરવા માટે નીચે એક પ્લેટફોર્મ પસંદ કરો' }, platformGrid: 'તમારું પ્લેટફોર્મ પસંદ કરો', downloader: { analyze: 'URL વિશ્લેષણ', parsing: 'વિશ્લેષણ ચાલુ છે...', subtitle: 'શરૂ કરવા માટે નીચે તમારી {platform} લિંક પેસ્ટ કરો.', defaultSubtitle: 'નીચે વિડિઓ લિંક પેસ્ટ કરો.', error: 'ડાઉનલોડ નિષ્ફળ' }, footer: { copyright: 'કોપીરાઈટ © 2026 StreamVault', links: ['અમારા વિશે', 'સંપર્ક', 'સેવાની શરતો', 'ગોપનીયતા નીતિ'] } },
  ur: { name: 'اردو', flag: '🇵🇰', dir: 'rtl', nav: { back: 'واپس' }, hero: { title1: 'کوئی بھی ویڈیو ڈاؤن لوڈ کریں', title2: 'مفت میں', subtitle: 'یوٹیوب، انسٹاگرام، ٹک ٹاک، فیس بک اور بہت کچھ', body: 'براہ راست اپنے ڈیوائس کی گیلری میں محفوظ کریں — کسی سائن اپ کی ضرورت نہیں۔', hint: '↓ شروع کرنے کے لیے نیچے ایک پلیٹ فارم منتخب کریں' }, platformGrid: 'اپنا پلیٹ فارم منتخب کریں', downloader: { analyze: 'یو آر ایل کا تجزیہ کریں', parsing: 'تجزیہ ہو رہا ہے...', subtitle: 'شروع کرنے کے لیے نیچے اپنا {platform} لنک پیسٹ کریں۔', defaultSubtitle: 'نیچے ویڈیو لنک پیسٹ کریں۔', error: 'تنزیل ناکام ہوگئی' }, footer: { copyright: 'جملہ حقوق محفوظ ہیں © 2026 StreamVault', links: ['ہمارے بارے میں', 'رابطہ کریں', 'سروس کی شرائط', 'پرائیویسی پالیسی'] } },
  es: { name: 'Español', flag: '🇪🇸', dir: 'ltr', nav: { back: 'Volver' }, hero: { title1: 'Descarga cualquier vídeo', title2: 'Gratis', subtitle: 'YouTube, Instagram, TikTok, Facebook y más', body: 'Guarda directamente en tu galería — sin registro.', hint: '↓ Elige una plataforma a continuación para comenzar' }, platformGrid: 'Elige tu plataforma', downloader: { analyze: 'Analizar URL', parsing: 'Analizando...', subtitle: 'Pega tu enlace de {platform} a continuación.', defaultSubtitle: 'Pega un enlace de vídeo a continuación.', error: 'Error en la descarga' }, footer: { copyright: 'Copyright © 2026 StreamVault', links: ['Sobre nosotros', 'Contacto', 'Términos de servicio', 'Política de privacidad'] } },
  fr: { name: 'Français', flag: '🇫🇷', dir: 'ltr', nav: { back: 'Retour' }, hero: { title1: 'Téléchargez n\'importe quelle vidéo', title2: 'Gratuitement', subtitle: 'YouTube, Instagram, TikTok, Facebook & plus encore', body: 'Enregistrez directement dans votre galerie — sans inscription.', hint: '↓ Choisissez une plateforme ci-dessous pour commencer' }, platformGrid: 'Choisissez votre plateforme', downloader: { analyze: 'Analyser l\'URL', parsing: 'Analyse...', subtitle: 'Collez votre lien {platform} ci-dessous.', defaultSubtitle: 'Collez un lien vidéo ci-dessous.', error: 'Échec du téléchargement' }, footer: { copyright: 'Copyright © 2026 StreamVault', links: ['À propos', 'Contact', 'Conditions d\'utilisation', 'Politique de confidentialité'] } },
  ru: { name: 'Русский', flag: '🇷🇺', dir: 'ltr', nav: { back: 'Назад' }, hero: { title1: 'Скачать любое видео', title2: 'Бесплатно', subtitle: 'YouTube, Instagram, TikTok, Facebook и др.', body: 'Сохраняйте прямо в галерею устройства — регистрация не нужна.', hint: '↓ Выберите платформу ниже, чтобы начать' }, platformGrid: 'Выберите платформу', downloader: { analyze: 'Анализировать URL', parsing: 'Анализ...', subtitle: 'Вставьте ссылку {platform} ниже.', defaultSubtitle: 'Вставьте ссылку на видео ниже.', error: 'Ошибка загрузки' }, footer: { copyright: 'Copyright © 2026 StreamVault', links: ['О нас', 'Контакты', 'Условия использования', 'Политика конфиденциальности'] } },
  ja: { name: '日本語', flag: '🇯🇵', dir: 'ltr', nav: { back: '戻る' }, hero: { title1: '動画をダウンロード', title2: '無料で', subtitle: 'YouTube, Instagram, TikTok, Facebook など', body: 'デバイスのギャラリーに直接保存 — 登録不要。', hint: '↓ 開始するにはプラットフォームを選択してください' }, platformGrid: 'プラットフォームを選択', downloader: { analyze: 'URLを分析', parsing: '解析中...', subtitle: '開始するには下に {platform} のリンクを貼り付けてください。', defaultSubtitle: '下に動画のリンクを貼り付けてください。', error: 'ダウンロードに失敗しました' }, footer: { copyright: '著作権 © 2026 StreamVault', links: ['会社概要', 'お問い合わせ', '利用規約', 'プライバシーポリシー'] } },
  zh: { name: '中文', flag: '🇨🇳', dir: 'ltr', nav: { back: '返回' }, hero: { title1: '下载任何视频', title2: '免费', subtitle: 'YouTube, Instagram, TikTok, Facebook 等', body: '直接保存到您的设备相册 — 无需注册。', hint: '↓ 选择下方平台以开始' }, platformGrid: '选择您的平台', downloader: { analyze: '分析链接', parsing: '正在解析...', subtitle: '在下方粘贴您的 {platform} 链接以开始。', defaultSubtitle: '在下方粘贴视频链接以开始。', error: '下载失败' }, footer: { copyright: '版权所有 © 2026 StreamVault', links: ['关于我们', '联系我们', '服务条款', '隐私政策'] } },
};

export default translations;
